import { StyleSheet} from 'react-native';
import { black, greenRarity, lightBlue, white } from '../../constants/colors';

export const stylesFilters= StyleSheet.create({
    container_style:{
        marginVertical:0,
        marginHorizontal:0,
        borderWidth:0,
        maxWidth:304, 
        width:'100%', 
        height:225, 
        justifyContent:'space-between', 
        flexWrap:'wrap',
        rowGap:8,
    },
    button_container_style:{
        flex:0, 
        maxWidth:210,
        borderRightWidth:0,
        borderRadius:8,
        backgroundColor:'#EEEEEE', 
        height:35,
    },
    text_style:{
        fontFamily:'MontserratAlt500',
        fontSize:14,
        color:'#000000',
    },
    h1:{
        fontFamily:'MontserratAlt700',
        fontSize:24,
    },
    h2:{
        fontFamily:'MontserratAlt500',
        fontSize:18,
        marginBottom:8,
    },
    wrapper_genres:{
        maxWidth:400, 
        width:'100%', 
        marginTop:10, 
        borderBottomWidth:3,
        borderBottomColor:'#CACACA'
    },
    button_container_rarity:{
        flex:0, 
        maxWidth:50,
        borderRightWidth:0,
        borderRadius:8,
        backgroundColor:'#EEEEEE', 
        width:50,
        height:50,
        padding:0,
    },
    select:{
        backgroundColor:greenRarity,
        height:45,
        borderRadius:8,
        paddingLeft:13,
        paddingRight:13,
    },
    text_btn:{
        fontFamily:'MontserratAlt700',
        fontSize:18,
        color:'white'
    },
    container_btn:{
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:lightBlue,
        padding:8,
        borderRadius:8,
        
    }
    
})